
#spring.datasource.url=jdbc:mysql://localhost:3306/helloProductDB-1591046?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=9376580as

#spring.datasource.initialization-mode=always

#management.security.enabled=false
#management.endpoints.web.exposure.include=*

#spring.jpa.hibernate.ddl-auto = create

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 9376580as
